#+STARTUP: showall
#+OPTIONS: toc:3
** Absicht
*** [[file:../assets/agenda/verbit_programme.txt][Misha Verbitsky's Programme]]
**** Fall I:

#+BEGIN_QUOTE

1. Метрическая геометрия и топология

А. Пополнение и вещественные числа
(на анализе можно дать аксиоматическое определение,
а тут заставить студентов все проверять, либо наоборот).
Последовательности Коши. Полнота.

Б. Метрические пространства. Норма в векторных
   пространствах. Приведение скалярного произведения
   к диагональному виду. Неравенство
   Коши-Буняковского-Шварца. Метрика на R^n.
   Эквивалентность норм. Нормированные кольца и поля.

В.  Пополнение. P-адические числа. *Теорема Островского.

Г. Компакты. Теорема Гейне-Бореля (секвенциональная
компактность в метрическом пространстве эквивалентна
обычной). Геодезические. *Теорема Хопфа-Ринова (локальная
компактность в полном метрическом пространстве равносильна
существованию геодезических). Внутренние метрики.

Д. Основы общей топологии. Дискретная, кодискретная
топология, аксиомы Хаусдорфа, аксиомы счетности,
экзотические примеры топологических
пространств. Сходимость последовательностей в
топологических пространствах. Гомеоморфизм, замыкание,
всюду плотные множества.

Е. Произведение топологических пространств. Топология
произведения и топология на R^n. Гильбертов
куб. Лемма Урысона (о существовании непрерывных функций
на хаусдорфовых нормальных пространствах). *Теорема о метризуемости
(хаусдорфово пространство со счетной базой метризуемо и
допускает вложение в гильбертов куб).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

2. Линейная алгебра и основы алгебры.

А. Группы, кольца, поля. Группа перестановок.
Аксиоматическое определение вещественных чисел.
Комплексные числа, сопряжение, модуль, деление
комплексных чисел.

Б. Действие группы на множестве. Гомоморфизм.
Каждая группа вкладывается в группу перестановок.
Нормальные подгруппы, диэдральная группа, симметрическая
группа, четверная группа Клейна, полупрямое произведение,
центральное расширение.

В. Делимость и алгоритм Евклида. Разложение на простые
множители. Идеалы, гауссовы числа, факториальные кольца, кольца
главных идеалов. Гомоморфизм колец, факторкольцо.
Неоднозначность разложения на простые в числовых
кольцах (примеры).

Г. Векторное пространство. Базис, размерность, линейная
независимость, тензорное произведение. Линейные операторы.
Алгебраические числа, иррациональные числа, трансцендентные числа.
Сумма, произведение, частное алгебраических чисел
алгебраично.

Д. Линейные формы, билинейные формы, полилинейные
формы, тензорное произведение. Двойственность и
ее свойства. Симплектические, евклидовы векторные пространства
и их группы автоморфизмов. Ортонормированный
базис, симплектический базис. Сигнатура квадратичной формы.

Е. Алгебры над
полем. Гиперкомплексные числа, кватернионы,
полиномы, алгебра Грассмана. Алгебры, заданные
образующими и соотношениями. Алгебра Клиффорда.

Ж. Алгебра Грассмана (подсчет размерности компонент).
Алгебра Грассмана (определитель). Мультипликативность
определителя. Тензорное произведение
алгебр. Алгебра Грассмана от суммы двух пространств.
Базис в алгебре Грассмана, явное выражение для
определителя. Матрица как способ записи линейного
оператора. Ранг матрицы. Обращение матриц
(явная формула). Определитель ортогональной
матрицы. Определитель симплектической матрицы.
Пфаффиан. Определитель Вандермонда.

З. Собственные значения и собственные векторы.
Приведение оператора к верхнетреугольной форме;
приведение коммутирующих операторов к верхнетреугольной
форме в одном и том же базисе.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

3. Основы анализа.

А. Предел, сходимость, предельные точки.

Б. Аксиоматическое определение вещественных чисел
(явная конструкция дается в "геометрии"). Сходимость
монотонной последовательности. *Сечение Дедекинда.

В. Сходимость рядов. Критерии сходимости. Степенные ряды.

Г. Абсолютная сходимость. Радиус сходимости ряда.
Умножение рядов. Разложение рациональных функций в степенной ряд.

Д. Непрерывные функции. Теорема о промежуточном значении.
Непрерывность полинома. Решение полиномиальных уравнений
нечетной степени.

Е. Дифференцируемые функции. Производная. Экстремум
функции. Исследование полиномиальных функций на экстремумы.
Явное вычисление производных. Правило Лейбница,
производная композиции, производная частного.
Производная как касательная к графику.

Ж. Правило Лопиталя.  Теорема
Лагранжа о приращении. Теорема Ролля.

З. Разложение функции в ряд Тэйлора. Формула Тэйлора
с остаточным членом. Аналитические функции.

И. Комплексные числа и движения R^2. Явное задание движений
через комплексные числа. Классификация движений.

К. Функции комплексной переменной. Экспонента, синус,
косинус, разложение в синуса и косинуса ряд. Основная теорема алгебры.

Л. Логарифм, разложение логарифма в ряд. Функциональные
тождества для логарифма и экспоненты.

М. Интеграл (наивное определение для непрерывных
функций на прямой). Формула Ньютона-Лейбница.
Интеграл как площадь под графиком.

Н. Символьное интегрирование. Интегралы от рациональных
функций, экспонент, произведения полиномов и экспонент
(с использованием линейных пространств).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

4. Комбинаторика и теория множеств.

А. Формальный метод Гильберта: системы аксиом евклидовой
геометрии от Евклида до Гильберта и Колмогорова.

Б. Простейшие аксиоматические структуры. Кванторы.
Исчисление высказываний.

В. Множества, функции. Соотношения эквивалентности и порядка.
Аксиомы Пеано и метод математической индукции.

Г. Счетные множества, несчетные множества.
Диагональный метод Кантора и парадоксы наивной теории множеств.

Д. Формальная теория множеств (обзор).
Теорема Кантора-Бернштейна. Континуум-гипотеза.

Е. Аксиома выбора, ординалы, теорема Цермело,
лемма Цорна.

Ж. Основы комбинаторики. Отображения конечных множеств.
Принцип Дирихле и биномиальные коэффициенты. Треугольник
Паскаля.

З. Степенные ряды и производящие функции. Числа Фибоначчи.

И. Треугольные числа. Разбиения и перестановки. Рекуррентные соотношения.

#+END_QUOTE
** Analysis

*** Harvard Math 55b

    + [[http://www.math.harvard.edu/~elkies/M55b.10/][Spring 2010 :elkies]]
    + [[http://www.math.harvard.edu/~ctm/home/text/class/harvard/55b/10/html/][Spring 2010 :ctm ]]


*** MIT

    + [[https://ocw.mit.edu/courses/mathematics/18-100b-analysis-i-fall-2010/index.htm][MIT 18.100B]]

*** HSE

    + [[https://math.hse.ru/calculus2016][HSE Analysis I]]

** Linear Algebra

*** Harvard Math 55a

    + [[http://www.math.harvard.edu/~ctm/home/text/class/harvard/55a/08/html/][Fall 2008]]
    + [[http://www.math.harvard.edu/~ctm/home/text/class/harvard/55a/09/html/index.html][Fall 2009]]
    + [[http://www.math.harvard.edu/~elkies/M55a.10/][Fall 2010]]
    + [[http://www.math.harvard.edu/~elkies/M55a.16/index.html][Fall 2016]]

*** MIT 18.700: Linear Algebra

    + [[http://www-math.mit.edu/~dav/700.html][Fall 2014]]

*** MIT 18.701: Algebra I

    + [[http://math.mit.edu/classes/18.701/index.html][Fall 2016]]

*** HSE 

    + [[https://sites.google.com/site/akhoroshkin/home/algebra_1_2016][HSE Algebra I]]

** Geometry

*** Geometry
    
    + [[https://math.hse.ru/geometry2016][HSE Geometry I]]

** Miscellaneous

*** [[http://yufeizhao.com/olympiad.html][Yufei Zhao's olympiad training handouts]]

*** [[http://www.mit.edu/~alexrem/Math%2520Competitions.html][Alexander Remorov's Math Competition Handouts]]

*** [[http://math.cmu.edu/~ploh/olympiad.shtml][Po-Shen Loh's Math Olympiad teaching notes]]

    - [[http://math.cmu.edu/~ploh/docs/math/mop2011/prob-method.pdf][Probabilistic Methods in Combinatorics 2011]]
    - [[http://math.cmu.edu/~ploh/docs/math/mop2012/combinatorics-black-soln.pdf][Probabilistic Methods in Combinatorics 2012]]
