#!/usr/bin/env bash
BLOG_DIR="/home/sdll/dev/sdll"
SOURCE_BRANCH=source

shopt -s extglob
function error_exit
{
   echo "$1" 1>&2
   exit 1
}

if [ -z "$1" ]
then
  echo "deploy script error: What changes did you make? Type a commit message."
  exit 1
fi

pushd $BLOG_DIR
# Build successfuly or exit
make rebuild-site
sleep 180
# Push changes on hakyll branch to github
git add -A
git commit -m "$1" || echo "Commited no changes."

# Switch to master branch
git checkout master

# delete old site
rm -rf !(.|..|.git|.gitignore|.nojekyll|.stack-work|_cache|_site)
mv _site/* $BLOG_DIR/
git add -A
git commit -m "$1"
git push origin master

# return to original branch
git checkout $SOURCE_BRANCH
git push origin $SOURCE_BRANCH
popd
