#+STARTUP: showall
#+OPTIONS: toc:3
** Absicht
*** Cryptography
- [[https://www.johannes-bauer.com/compsci/ecc/][Introduction to ECC]]
*** Program

The program is based on [[file:../files/assets/agenda/verbit_programme.txt][Misha Verbitsky's Curriculum]].

**** Metric Geometry and Topology

------------------------------------------------------------
Литература.
------------------------------------------------------------

/cf. [[http://bogomolov-lab.ru/KURSY/TOP-2012/][HSE 2012 Course in Topology]]/

+ [[http://www.pdmi.ras.ru/~olegviro/topoman/e-unstable.pdf][Elementary Topology. Textbook in Problems by O.Ya.Viro, O.A.Ivanov, V.M.Kharlamov, N.Y.Netsvetaev]]
+ [[http://verbit.ru/MATH/UCHEBNIK/top-book.pdf][Вербицкий М., Топология в задачах]]
+ [[http://www.math.psu.edu/petrunin/papers/alexandrov/bbi.pdf][Бураго Д. Ю., Бураго Ю. Д, Иванов С. В. A Course in Metric Geometry ]]
+ Misha Gromov. Metric structures for Riemannian and non-Riemannian spaces

А. Пополнение и вещественные числа
(на анализе можно дать аксиоматическое определение,
а тут заставить студентов все проверять, либо наоборот).
Последовательности Коши. Полнота.

Б. Метрические пространства. Норма в векторных
   пространствах. Приведение скалярного произведения
   к диагональному виду. Неравенство
   Коши-Буняковского-Шварца. Метрика на R^n.
   Эквивалентность норм. Нормированные кольца и поля.

В.  Пополнение. P-адические числа. *Теорема Островского.

Г. Компакты. Теорема Гейне-Бореля (секвенциональная
компактность в метрическом пространстве эквивалентна
обычной). Геодезические. *Теорема Хопфа-Ринова (локальная
компактность в полном метрическом пространстве равносильна
существованию геодезических). Внутренние метрики.

Д. Основы общей топологии. Дискретная, кодискретная
топология, аксиомы Хаусдорфа, аксиомы счетности,
экзотические примеры топологических
пространств. Сходимость последовательностей в
топологических пространствах. Гомеоморфизм, замыкание,
всюду плотные множества.

Е. Произведение топологических пространств. Топология
произведения и топология на R^n. Гильбертов
куб. Лемма Урысона (о существовании непрерывных функций
на хаусдорфовых нормальных пространствах). *Теорема о метризуемости
(хаусдорфово пространство со счетной базой метризуемо и
допускает вложение в гильбертов куб).

**** Linear and Basic Algebra

------------------------------------------------------------
Литература.
------------------------------------------------------------
+ А. Шень. Простые и составные числа
+ И. Л. Кантор, А. С. Солодовников. Гиперкомплексные числа.
+ И. М. Гельфанд, А. Шень. Алгебра.
+ [[http://www.mccme.ru/free-books/pdf/alekseev.pdf][В. Б. Алексеев. Теорема Абеля в задачах и решениях.]] ([[http://www.maths.ed.ac.uk/~aar/papers/abel.pdf][Abel's Theorem in Problems and Solutions]])
+ М. М. Постников. Введение в теорию алгебраических чисел.
+ И. Р. Шафаревич. Основные понятия алгебры.
+ [[http://www.math.ru/lib/files/djvu/chislo.djvu][А. А. Кириллов. Что такое число?]]
+ А. И. Кострикин, Ю. И. Манин, Линейная алгебра и геометрия.
+ М.М. Постников. Лекции по геометрии. Линейная алгебра
+ S. Axler. "Linear algebra done Right"

А. Группы, кольца, поля. Группа перестановок.
Аксиоматическое определение вещественных чисел.
Комплексные числа, сопряжение, модуль, деление
комплексных чисел.

Б. Действие группы на множестве. Гомоморфизм.
Каждая группа вкладывается в группу перестановок.
Нормальные подгруппы, диэдральная группа, симметрическая
группа, четверная группа Клейна, полупрямое произведение,
центральное расширение.

В. Делимость и алгоритм Евклида. Разложение на простые
множители. Идеалы, гауссовы числа, факториальные кольца, кольца
главных идеалов. Гомоморфизм колец, факторкольцо.
Неоднозначность разложения на простые в числовых
кольцах (примеры).

Г. Векторное пространство. Базис, размерность, линейная
независимость, тензорное произведение. Линейные операторы.
Алгебраические числа, иррациональные числа, трансцендентные числа.
Сумма, произведение, частное алгебраических чисел
алгебраично.

Д. Линейные формы, билинейные формы, полилинейные
формы, тензорное произведение. Двойственность и
ее свойства. Симплектические, евклидовы векторные пространства
и их группы автоморфизмов. Ортонормированный
базис, симплектический базис. Сигнатура квадратичной формы.

Е. Алгебры над
полем. Гиперкомплексные числа, кватернионы,
полиномы, алгебра Грассмана. Алгебры, заданные
образующими и соотношениями. Алгебра Клиффорда.

Ж. Алгебра Грассмана (подсчет размерности компонент).
Алгебра Грассмана (определитель). Мультипликативность
определителя. Тензорное произведение
алгебр. Алгебра Грассмана от суммы двух пространств.
Базис в алгебре Грассмана, явное выражение для
определителя. Матрица как способ записи линейного
оператора. Ранг матрицы. Обращение матриц
(явная формула). Определитель ортогональной
матрицы. Определитель симплектической матрицы.
Пфаффиан. Определитель Вандермонда.

З. Собственные значения и собственные векторы.
Приведение оператора к верхнетреугольной форме;
приведение коммутирующих операторов к верхнетреугольной
форме в одном и том же базисе.

**** Real Analysis

 ------------------------------------------------------------
 Литература:
 ------------------------------------------------------------

+ Лоран Шварц. Анализ.
+ В. А. Зорич. Математический анализ.
+ У. Рудин. Основы математического анализа.
+ Б. Гелбаум, Дж. Олмстед. Контрпримеры в анализe.
+ Зельдович Я.Б., Яглом И.М. Высшая математика для начинающих физиков и техников.
+ С. И. Шварцбурд, О. С. Ивашев-Мусатов. Алгебра и начала
  анализа. Учебное пособие для ПТУ.
+ C. Pugh. Real Mathematical Analysis

 А. Предел, сходимость, предельные точки.

 Б. Аксиоматическое определение вещественных чисел
 (явная конструкция дается в "геометрии"). Сходимость
 монотонной последовательности. *Сечение Дедекинда.

 В. Сходимость рядов. Критерии сходимости. Степенные ряды.

 Г. Абсолютная сходимость. Радиус сходимости ряда.
 Умножение рядов. Разложение рациональных функций в степенной ряд.

 Д. Непрерывные функции. Теорема о промежуточном значении.
 Непрерывность полинома. Решение полиномиальных уравнений
 нечетной степени.

 Е. Дифференцируемые функции. Производная. Экстремум
 функции. Исследование полиномиальных функций на экстремумы.
 Явное вычисление производных. Правило Лейбница,
 производная композиции, производная частного.
 Производная как касательная к графику.

 Ж. Правило Лопиталя.  Теорема
 Лагранжа о приращении. Теорема Ролля.

 З. Разложение функции в ряд Тэйлора. Формула Тэйлора
 с остаточным членом. Аналитические функции.

 И. Комплексные числа и движения R^2. Явное задание движений
 через комплексные числа. Классификация движений.

 К. Функции комплексной переменной. Экспонента, синус,
 косинус, разложение в синуса и косинуса ряд. Основная теорема алгебры.

 Л. Логарифм, разложение логарифма в ряд. Функциональные
 тождества для логарифма и экспоненты.

 М. Интеграл (наивное определение для непрерывных
 функций на прямой). Формула Ньютона-Лейбница.
 Интеграл как площадь под графиком.

 Н. Символьное интегрирование. Интегралы от рациональных
 функций, экспонент, произведения полиномов и экспонент
 (с использованием линейных пространств).

 
**** Logic and Discrete Mathematics

/cf. [[http://www.mi.ras.ru/~bekl/logic2014.html][HSΕ 2014/2015 Course in Logic and Algorithms]]/
 ------------------------------------------------------------
 Литература.
 ------------------------------------------------------------
+ [[http://www.mccme.ru/free-books/shen/shen-logic-part1-2.pdf][Н. К. Верещагин, А. Шень. Начала теории множеств.]]
+ Дуглас Р. Хофстадтер. Гедель, Эшер, Бах: эта бесконечная
  гирлянда. Метафорическая фуга о разуме и машинах в духе Льюиса
  Кэрролла.
+ Реймонд Смаллиан. Как же называется эта книга?
+ Реймонд Смаллиан. Принцесса или тигр?
+ Реймонд Смаллиан. Алиса в стране смекалки
+ Мартин Гарднер. Крестики-нолики
+ Мартин Гарднер. От мозаик Пенроуза к надёжным шифрам
+ Ричард Ф.Фейнман. Вы, конечно, шутите, мистер Фейнман!
+ А. Шень. Игры и стратегии с точки зрения математики
+ А. Шень. Математическая индукция
+ А. Гротендик. Урожаи и посевы.
+ В. И. Арнольд. Гюйгенс и Барроу, Ньютон и Гук
+ Ю. И. Манин. Математика как метафора.
+ Misha Gromov. Ergostuctures, Ergologic and the Universal Learning Problem.
+ Г. Харди. Апология математика.
+ П. Локхарт. Плач математика.
+ М. Кац, С. Улам. Математика и логика.
+ А. Шень. Программирование. Теоремы и задачи
+ А. Шень. Задачи по математике, предлагавшиеся ученикам
+ математического класса 57 школы
+ П. С. Александров, А. И. Маркушевич, А. Я. Хинчин (ред.)
  Энциклопедия элементарной математики (6 томов).
+ Б. М. Давидович, П. Е. Пушкарь, Ю. В. Чеканов. Математический анализ
  в 57-й школе. Четырехгодичный курс
+ Барвейс (ред.) Справочная книга по математической логике

 А. Формальный метод Гильберта: системы аксиом евклидовой
 геометрии от Евклида до Гильберта и Колмогорова.

 Б. Простейшие аксиоматические структуры. Кванторы.
 Исчисление высказываний.

 В. Множества, функции. Соотношения эквивалентности и порядка.
 Аксиомы Пеано и метод математической индукции.

 Г. Счетные множества, несчетные множества.
 Диагональный метод Кантора и парадоксы наивной теории множеств.

 Д. Формальная теория множеств (обзор).
 Теорема Кантора-Бернштейна. Континуум-гипотеза.

 Е. Аксиома выбора, ординалы, теорема Цермело,
 лемма Цорна.

 Ж. Основы комбинаторики. Отображения конечных множеств.
 Принцип Дирихле и биномиальные коэффициенты. Треугольник
 Паскаля.

 З. Степенные ряды и производящие функции. Числа Фибоначчи.

 И. Треугольные числа. Разбиения и перестановки. Рекуррентные соотношения.

** Analysis

*** Harvard Math 55b

    + [[http://www.math.harvard.edu/~elkies/M55b.10/][Spring 2010 :elkies]]
    + [[http://www.math.harvard.edu/~ctm/home/text/class/harvard/55b/10/html/][Spring 2010 :ctm ]]


*** MIT

    + [[https://ocw.mit.edu/courses/mathematics/18-100b-analysis-i-fall-2010/index.htm][MIT 18.100B]]

*** HSE

    + [[https://math.hse.ru/calculus2016][HSE Analysis I]]

** Linear Algebra

*** Harvard Math 55a

    + [[http://www.math.harvard.edu/~ctm/home/text/class/harvard/55a/08/html/][Fall 2008]]
    + [[http://www.math.harvard.edu/~ctm/home/text/class/harvard/55a/09/html/index.html][Fall 2009]]
    + [[http://www.math.harvard.edu/~elkies/M55a.10/][Fall 2010]]
    + [[http://www.math.harvard.edu/~elkies/M55a.16/index.html][Fall 2016]]

*** MIT 18.700: Linear Algebra

    + [[http://www-math.mit.edu/~dav/700.html][Fall 2014]]

*** MIT 18.701: Algebra I

    + [[http://math.mit.edu/classes/18.701/index.html][Fall 2016]]

*** HSE 

    + [[https://sites.google.com/site/akhoroshkin/home/algebra_1_2016][HSE Algebra I]]

** Geometry

*** HSE
    
    + [[https://math.hse.ru/geometry2016][HSE Geometry I]]

** Miscellaneous

- [[http://yufeizhao.com/olympiad.html][Yufei Zhao's olympiad training handouts]]
- [[http://www.mit.edu/~alexrem/Math%2520Competitions.html][Alexander Remorov's Math Competition Handouts]]
- [[http://math.cmu.edu/~ploh/olympiad.shtml][Po-Shen Loh's Math Olympiad teaching notes]]
  + [[http://math.cmu.edu/~ploh/docs/math/mop2011/prob-method.pdf][Probabilistic Methods in Combinatorics 2011]]
  + [[http://math.cmu.edu/~ploh/docs/math/mop2012/combinatorics-black-soln.pdf][Probabilistic Methods in Combinatorics 2012]]
